name: Publish to NuGet

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    types: [closed]
#    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  publish:
    runs-on: windows-latest
    env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
       
    steps:
    - uses: actions/checkout@v2
          
    - name: Setup .NET Core 2.1	
      uses: actions/setup-dotnet@v1	
      with:	
        dotnet-version: 2.1.x	
    
    - name: Setup .NET Core 3.1	
      uses: actions/setup-dotnet@v1	
      with:	
        dotnet-version: 3.1.x
    
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Install dependencies
      run: dotnet restore DapperExtensions.sln
      
    - name: Build
      run: dotnet build DapperExtensions --configuration Release --no-restore
      
#    - name: Publish
#      uses: brandedoutcast/publish-nuget@v2.5.2
#      with:
#          PROJECT_FILE_PATH: MintPlayer.SeasonChecker/MintPlayer.SeasonChecker.csproj
#          NUGET_KEY: ${{secrets.PUBLISH_TO_NUGET_ORG}}
#          INCLUDE_SYMBOLS: true

    - name: Pack Default Version
      run: dotnet pack --no-build --configuration Release ./DapperExtensions/DapperExtensions.csproj --output .
      
#    - name: Upload Artifact for Default Version
#      uses: actions/upload-artifact@v1.0.0
#      with:
#        name: nuget_package
#        path: bin\Release\*.nupkg

#    - name: Pack Signed Version
#      run: dotnet pack --no-build --configuration Release ./DapperExtensions.StrongName/DapperExtensions.StrongName.csproj --output .
      
    - name: Upload Artifact for Signed Version
      uses: actions/upload-artifact@v2
      with:
        name: nuget_packages
        path: .\*.nupkg

#   - name: PushNuget
#      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
#      run: dotnet nuget push *.nupkg

